site_name: 'SWTCDocs Demo'
pages:
- '公链介绍':
    - 'SWTC公链': 'index.md'
    - 'SWTC通证': 'intro/swtctoken.md'
    - '社区及资源': 'intro/resources.md'
    - '基金会及历史': 'intro/foundation.md'
    - '生态节点计划': 'intro/nodestrategy.md'
- 'Wiki':
    - '资产': 'wiki/asset.md'
    - '账本结构': 'wiki/ledgerstructure.md'
    - '交易结构': 'wiki/txstructure.md'
- '开发参考':
    - 'jingtum-lib手册': 'reference/jingtum-lib.md'
    - 'Service节点手册': 'reference/servicenode.md'
    - 'SDKs': 'reference/sdks.md'
- '其他':
    - 'Jingtum-lib使用教程': 'tutorial/jingtum-lib_tutorial.md'
    - 'Service节点使用教程': 'tutorial/service_tutorial.md'
    - '通证发行流程': 'tutorial/token_issue.md'
    - 'SWTC Labs': 'tutorial/swtclabs.md'
- '关于': 'about.md'
extra_css: ['docs/bootstrap/css']
extra_javascript: ['docs/bootstrap/js']
theme_dir: 'docs/bootstrap'
repo_url: 'https://github.com/penlylu/swtcdocsdemo'
