site_name: 'SWTCDocs Demo'
pages:
- '公链介绍':
    - 'SWTC公链': 'index.md'
    - 'SWTC通证': 'intro/swtctoken.md'
    - '社区及资源': 'intro/resources.md'
    - '基金会及历史': 'intro/foundation.md'
    - '生态节点计划': 'intro/nodestrategy.md'
- '概念':
    - '账户': 'concepts/account.md'
    - '银关': 'concepts/fingate.md'
    - '资产': 'concepts/asset.md'
    - '费用': 'concepts/fee.md'
    - '撮合交易': 'concepts/exchange.md'
    - '账本': 'concepts/ledger.md'
    - '节点': 'concepts/node.md'
    - '集群': 'concepts/cluster.md'
    - '测试网': 'concepts/testnet.md'
- '开发参考':
    - 'jingtum-lib手册': 'reference/jingtum-lib.md'
    - 'SDKs': 'reference/sdks.md'
    - 'Service节点手册': 'reference/servicenode.md'
- '关于': 'about.md'
- '其他':
    - 'Jingtum-lib使用教程': 'tutorial/jingtum-lib_tutorial.md'
    - 'Service节点使用教程': 'tutorial/service_tutorial.md'
    - '通证发行流程': 'tutorial/token_issue.md'
    - 'SWTC Labs': 'tutorial/swtclabs.md'
extra_css: ['docs/bootstrap/css']
extra_javascript: ['docs/bootstrap/js']
theme_dir: 'docs/bootstrap'
repo_url: 'https://github.com/penlylu/swtcdocsdemo'
